site_name: Minha documentação
site_url: http://github.com/BrunoBReis/test-docs

nav:
  - Home: index.md
  - Como contribuir: contribuir.md
  - Sprint:
      - Sprint0: sprints/sprint0.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
